server.port=8080
spring.application.name=api-gateway

# Eureka connection
eureka.client.service-url.defaultZone=http://smartsop-discovery:8761/eureka/

# Enable discovery-based routing
spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true


# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true


# ==========================================
# Spring Cloud Gateway Routes Configuration
# ==========================================
#spring.cloud.gateway.server.webmvc.routes[0].id=order-service
#spring.cloud.gateway.server.webmvc.routes[0].uri=lb://ORDER-SERVICE
#spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/orders/**
#spring.cloud.gateway.server.webmvc.routes[0].filters[0].name=CircuitBreaker
#spring.cloud.gateway.server.webmvc.routes[0].filters[0].args.name=orderCircuitBreaker
#spring.cloud.gateway.server.webmvc.routes[0].filters[0].args.fallbackUri=forward:/fallback/order
#
#spring.cloud.gateway.server.webmvc.routes[1].id=user-service
#spring.cloud.gateway.server.webmvc.routes[1].uri=lb://USER-SERVICE
#spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/users/**
#spring.cloud.gateway.server.webmvc.routes[1].filters[0].name=CircuitBreaker
#spring.cloud.gateway.server.webmvc.routes[1].filters[0].args.name=userCircuitBreaker
#spring.cloud.gateway.server.webmvc.routes[1].filters[0].args.fallbackUri=forward:/fallback/user
#
#spring.cloud.gateway.server.webmvc.routes[2].id=product-service
#spring.cloud.gateway.server.webmvc.routes[2].uri=lb://PRODUCT-SERVICE
#spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/products/**
#spring.cloud.gateway.server.webmvc.routes[2].filters[0].name=CircuitBreaker
#spring.cloud.gateway.server.webmvc.routes[2].filters[0].args.name=productCircuitBreaker
#spring.cloud.gateway.server.webmvc.routes[2].filters[0].args.fallbackUri=forward:/fallback/product


# ==========================================
# Resilience4j Circuit Breaker Configurations
# ==========================================
resilience4j.circuitbreaker.instances.orderCircuitBreaker.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.orderCircuitBreaker.sliding-window-size=10
resilience4j.circuitbreaker.instances.orderCircuitBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.orderCircuitBreaker.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.orderCircuitBreaker.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.orderCircuitBreaker.automatic-transition-from-open-to-half-open-enabled=true

resilience4j.circuitbreaker.instances.userCircuitBreaker.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.userCircuitBreaker.sliding-window-size=10
resilience4j.circuitbreaker.instances.userCircuitBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.userCircuitBreaker.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.userCircuitBreaker.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.userCircuitBreaker.automatic-transition-from-open-to-half-open-enabled=true

resilience4j.circuitbreaker.instances.productCircuitBreaker.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.productCircuitBreaker.sliding-window-size=10
resilience4j.circuitbreaker.instances.productCircuitBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.productCircuitBreaker.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.productCircuitBreaker.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.productCircuitBreaker.automatic-transition-from-open-to-half-open-enabled=true


# ==========================================
# Resilience4j Time Limiter Configurations
# ==========================================
resilience4j.timelimiter.instances.orderCircuitBreaker.timeout-duration=3s
resilience4j.timelimiter.instances.userCircuitBreaker.timeout-duration=3s
resilience4j.timelimiter.instances.productCircuitBreaker.timeout-duration=3s


# Zipkin - send all traces (1.0 = 100%, use 0.1 in production)
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]