spring.application.name=discovery-service
server.port=8761

# Prevent Eureka from registering with itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Define the service URL using the container name instead of localhost
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
